version: '3.8'

services:
  customer-mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customer
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  shopping-postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root_username
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: orders
    networks:
      - my_network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: products
      MONGO_INITDB_ROOT_USERNAME: root_username
      MONGO_INITDB_ROOT_PASSWORD: root_password
    networks:
      - my_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


networks:
  my_network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  mongo-data:
